spring:
  application:
    name: ticket-management
  datasource:
    url: jdbc:mysql://localhost:3306/ticket
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zyh790201
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射开关
    map-underscore-to-camel-case: true

# 微信测试号配置
wechat:
  test:
    app-id: wx94cd5b487e8b7509  # 替换为你的测试号AppID
    app-secret: 047b3810f687c2dfd2fd6033181345cf # 替换为你的测试号AppSecret
    redirect-uri: http://e269359e.natappfree.cc/api/auth/wechat/callback  # 本地测试回调地址